spring:
  application:
    name: dynamic-thread-pool-test-app

server:
  port: 8089

dynamic:
  thread:
    pool:
      config:
        # 状态；true = 开启、false 关闭
        enable: true
        # redis host
        host: localhost
        # redis port
        port: 6379
        password:

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
